import { StyleSheet } from 'react-native';

// Shared customer module styles reused by the main container, header, and screen components.
export const customerStyles = StyleSheet.create({
  page: {
    flex: 1,
  },
  splashPage: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  splashWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingTop: 14,
    gap: 12,
  },
  signupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  authCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
    gap: 12,
  },
  authTitle: {
    fontSize: 24,
    fontWeight: '900',
  },
  authSub: {
    fontSize: 14,
    lineHeight: 21,
  },
  helperText: {
    fontSize: 12,
    lineHeight: 18,
  },
  input: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
  },
  inputMultiline: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  header: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  homeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  homeLogoWrap: {
    minWidth: 82,
    alignItems: 'flex-start',
  },
  headerSearchFlex: {
    flex: 1,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 0,
    gap: 10,
  },
  homeUtilityRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    rowGap: 10,
    gap: 10,
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  iconBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 17,
    height: 17,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  iconBadgeText: {
    fontSize: 9,
    fontWeight: '900',
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
  },
  searchIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationBar: {
    marginTop: 10,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  locationBarInline: {
    marginTop: 0,
    minWidth: 220,
    flexGrow: 1,
    flex: 1,
  },
  locationCopy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    minWidth: 0,
    flex: 1,
  },
  locationText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  locationAction: {
    fontSize: 13,
    fontWeight: '800',
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  utilityChip: {
    borderWidth: 1,
    borderRadius: 14,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  utilityChipText: {
    fontSize: 12,
    fontWeight: '800',
  },
  shortcutRow: {
    marginTop: 2,
  },
  shortcutChip: {
    minWidth: 104,
    flexGrow: 1,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  shortcutChipText: {
    fontSize: 13,
    fontWeight: '800',
  },
  horizontalRow: {
    gap: 12,
    paddingRight: 4,
    paddingVertical: 4,
  },
  bannerCard: {
    borderWidth: 1,
    borderRadius: 20,
    overflow: 'hidden',
    padding: 14,
    gap: 8,
  },
  bannerAccent: {
    height: 92,
    borderRadius: 16,
  },
  bannerTitle: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 24,
  },
  bannerText: {
    fontSize: 13,
    lineHeight: 20,
    minHeight: 40,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryCard: {
    borderWidth: 1,
    borderRadius: 20,
    minHeight: 106,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryLabel: {
    marginTop: 10,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 15,
  },
  productCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
  },
  productThumb: {
    height: 120,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productThumbText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0a1624',
  },
  productTitle: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 19,
  },
  productMeta: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 18,
  },
  productPrice: {
    marginTop: 8,
    fontSize: 22,
    fontWeight: '900',
  },
  dealGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  dealCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
  },
  dealThumb: {
    height: 90,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dealThumbText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0a1624',
  },
  dealTitle: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  dealMeta: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 18,
  },
  dealPrice: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '900',
  },
  searchPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchPillText: {
    fontSize: 12,
    fontWeight: '700',
  },
  searchCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  searchCardCompact: {
    flexDirection: 'column',
  },
  searchCardThumb: {
    width: 112,
    height: 144,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchCardThumbText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#0a1624',
  },
  searchCardThumbCompact: {
    width: '100%',
    height: 132,
  },
  searchCardBody: {
    flex: 1,
  },
  searchCardTitle: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  searchCardMeta: {
    marginTop: 5,
    fontSize: 12,
    lineHeight: 18,
  },
  searchCardPrice: {
    marginTop: 8,
    fontSize: 24,
    fontWeight: '900',
  },
  detailCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 14,
  },
  detailThumb: {
    height: 220,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailThumbText: {
    fontSize: 48,
    fontWeight: '900',
    color: '#0a1624',
  },
  detailTitle: {
    marginTop: 14,
    fontSize: 24,
    fontWeight: '900',
  },
  detailSubTitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
  },
  detailPrice: {
    marginTop: 10,
    fontSize: 30,
    fontWeight: '900',
  },
  detailDescription: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 22,
  },
  subSectionTitle: {
    marginTop: 16,
    marginBottom: 8,
    fontSize: 16,
    fontWeight: '800',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  infoTag: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  infoTagText: {
    fontSize: 12,
    fontWeight: '700',
  },
  pharmacyCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    gap: 10,
  },
  pharmacyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  pharmacyHeaderCopy: {
    flex: 1,
  },
  pharmacyName: {
    fontSize: 16,
    fontWeight: '800',
  },
  pharmacyPrice: {
    fontSize: 22,
    fontWeight: '900',
  },
  pharmacyMeta: {
    fontSize: 12,
    lineHeight: 18,
  },
  pharmacyStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 14,
    gap: 8,
  },
  addressCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    gap: 10,
  },
  notificationCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  notificationUnread: {
    borderLeftWidth: 4,
  },
  notificationMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  infoTitle: {
    flexShrink: 1,
    fontSize: 17,
    fontWeight: '800',
  },
  infoLine: {
    fontSize: 13,
    lineHeight: 19,
  },
  orderStatus: {
    fontSize: 13,
    fontWeight: '800',
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '800',
  },
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
  },
  quantityValue: {
    minWidth: 28,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
  },
  billBox: {
    marginTop: 12,
    borderRadius: 16,
    padding: 12,
    backgroundColor: 'rgba(77, 168, 255, 0.08)',
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  billText: {
    fontSize: 13,
  },
  billTotal: {
    fontSize: 16,
    fontWeight: '900',
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  halfInput: {
    flexGrow: 1,
    minWidth: 140,
  },
  optionCard: {
    borderWidth: 1,
    borderRadius: 18,
    minHeight: 126,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  optionTitle: {
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 18,
  },
  sortPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  sortPillText: {
    fontSize: 12,
    fontWeight: '800',
  },
  trackRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
  },
  trackDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    marginTop: 4,
  },
  trackCopy: {
    flex: 1,
  },
  trackTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  trackMeta: {
    marginTop: 4,
    fontSize: 12,
  },
  inlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  inlineRowStack: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  actionButton: {
    minHeight: 46,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionButtonLabel: {
    fontSize: 13,
    fontWeight: '800',
  },
  fullWidth: {
    alignSelf: 'stretch',
  },
});
